services:
  frontend:
    build: frontend
    environment:
      HTTPS_METHOD: noredirect
      VIRTUAL_HOST: dev.personal.test
      VIRTUAL_PORT: 80
      VIRTUAL_PROTO: http
    expose:
      - 80
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

